server:
  port: 9100
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/houxi1234/config.git
          searchPaths: repo
      label: master
#    bus:
#      trace:
#        enabled: true
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
    ip-address: 119.3.66.33
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh